### ISSUE TITLE
bun run setup/ bun run start err

### ISSUE THREAD

**Issue by teame-sy** [uiovasot/not-seed#1]
![Uploading notseedbunrun.png…]()

**Comment by teame-sy** [comment]
![notseedbunrun](https://github.com/user-attachments/assets/ff38e384-e711-4e4d-9f27-e10e170e2fda)

**Comment by uiovasot** [comment]
bun run setup은 가장 처음에만 하면 되고, 다음 실행에서는 bun run start만 하면 됩니다

**Comment by teame-sy** [comment]
근데 bun run start 에서 에러 뜨는ㄷ

**Comment by teame-sy** [comment]
맨 마지막 커맨드를 봐주세요

**Comment by uiovasot** [comment]
아 bun run build 한번 해보세요
